# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10FOW0fwRM1qSwFml1Lx1NMVnUL9iOl7D
"""

print("Hello Python")